### ISSUE TITLE
Suggested changes

### ISSUE THREAD

**Issue by virsto** [WillKoehrsen/Machine-Learning-Projects#1]
1) I suggest that you modify the following functions to include an additional argument; i.e.

  ```
RandomizedSearchCV(...,return_train_score=True,...)
  GridSearchCV(...,return_train_score=True,...)
```
  
This should eliminate many irritating warning messages when one is using
the more recent versions of the imported python packages for Python 3+.

2) The following needs to be edited:

> Training Curves
> 
> We can perform grid search over only one parameter to observe the effects of changing that parameter on performance. We will look at training time, training set accuracy, and **teseting** set accuracy.

3) In: [(http://localhost:8889/notebooks/random_forest_explained/Random%20Forest%20Explained.ipynb)]

where you have code for:

> Data Preparation
> One-Hot Encoding

IMHO you should show that you are using 7 days not 5 days for the analysis.

**Comment by WillKoehrsen** [comment]
Thank you for the suggestions. I implemented all the changes.
