### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by varsha1288** [WillKoehrsen/Machine-Learning-Projects#3]

**Comment by WillKoehrsen** [comment]
I'm sorry, but could you please explain which file you are referencing and which weights?

**Comment by varsha1288** [comment]
Hi,

Your code seems really nice.
I am trying to use it for my problem statement.

I have my code.
But I am giving in the layers manually.
In your code it is automated.

I am trying to utilize your code to modify mine. But unfortunately not
great at programming.

Sorry for the trouble.

Thanks,
Varsha
